export interface OutputRegistryEntry {
  id: string;
  label: string;
  description: string;
  transport: 'stream' | 'event' | 'response' | 'webhook';
  mimeType: string;
  sampleRate?: number;
  canBecomeApiCall: boolean;
}

export const outputRegistry: OutputRegistryEntry[] = [
  {
    id: "audio_output",
    label: "Audio Output",
    description: "PCM audio generated by Pluto 1.0 Live.",
    transport: "stream",
    mimeType: "audio/pcm",
    sampleRate: 24000,
    canBecomeApiCall: true
  },
  {
    id: "audio_stream",
    label: "Audio Stream",
    description: "Continuous real-time audio playback channel.",
    transport: "stream",
    mimeType: "audio/pcm",
    sampleRate: 24000,
    canBecomeApiCall: true
  },
  {
    id: "text_output",
    label: "Text Output",
    description: "Text contents parsed from server responses.",
    transport: "response",
    mimeType: "text/plain",
    canBecomeApiCall: true
  },
  {
    id: "input_transcript",
    label: "Input Transcript",
    description: "Local speech-to-text live transcription results.",
    transport: "event",
    mimeType: "text/plain",
    canBecomeApiCall: false
  },
  {
    id: "output_transcript",
    label: "Output Transcript",
    description: "Completed assistant voice transcription segments.",
    transport: "event",
    mimeType: "text/plain",
    canBecomeApiCall: true
  },
  {
    id: "tool_call",
    label: "Tool Call",
    description: "Function invocation trigger emitted by the intelligent agent.",
    transport: "event",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "tool_response",
    label: "Tool Response",
    description: "Outcome values supplied back to coordinate agent turns.",
    transport: "response",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "tool_call_cancellation",
    label: "Tool Call Cancellation",
    description: "Signal to abort in-flight background function threads.",
    transport: "event",
    mimeType: "application/json",
    canBecomeApiCall: false
  },
  {
    id: "turn_complete",
    label: "Turn Complete",
    description: "Eburon model is finished streaming text or acoustic waveforms.",
    transport: "event",
    mimeType: "application/json",
    canBecomeApiCall: false
  },
  {
    id: "server_interruption",
    label: "Server Interruption",
    description: "Indicates that the user cut-off the streaming agent voice.",
    transport: "event",
    mimeType: "application/json",
    canBecomeApiCall: false
  },
  {
    id: "error",
    label: "Error Notification",
    description: "Relays system connection and validation error models.",
    transport: "response",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "model_content",
    label: "Model Content",
    description: "Raw response payloads container matching API requirements.",
    transport: "response",
    mimeType: "application/json",
    canBecomeApiCall: false
  },
  {
    id: "calendar_event_created",
    label: "Calendar Event Created",
    description: "Result parameters from calendar booking integration.",
    transport: "webhook",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "email_draft_or_sent",
    label: "Email Drafted or Sent",
    description: "Outbound message draft or dispatch confirmation log.",
    transport: "webhook",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "reminder_created",
    label: "Reminder Created",
    description: "Timestamp and title details of set reminder tasks.",
    transport: "webhook",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "route_result",
    label: "Route Result",
    description: "Turn-by-turn routing matrix calculations.",
    transport: "response",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "nearby_places_result",
    label: "Nearby Places Result",
    description: "Spatial search result clusters for geofencing and locations.",
    transport: "response",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "traffic_info_result",
    label: "Traffic Info Result",
    description: "Real-time delay index indicators from target sectors.",
    transport: "response",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "order_status_result",
    label: "Order Status Result",
    description: "Full transit logs and delivery ETAs lookup.",
    transport: "response",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "return_request_started",
    label: "Return Request Started",
    description: "Signals initiations of package returns.",
    transport: "webhook",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "representative_handoff",
    label: "Representative Handoff",
    description: "Transfers the line context to live customer service personnel.",
    transport: "webhook",
    mimeType: "application/json",
    canBecomeApiCall: true
  },
  {
    id: "video_websdk_stream",
    label: "Video WebSDK Stream",
    description: "High-throughput h264/VP8 video streaming channels for real-time visual grounding.",
    transport: "stream",
    mimeType: "video/h264",
    canBecomeApiCall: true
  },
  {
    id: "screenshare_active",
    label: "Screenshare Active",
    description: "Periodic screen frame base64 transfers for viewport grounding context.",
    transport: "event",
    mimeType: "application/json",
    canBecomeApiCall: true
  }
];
